#!/usr/bin/python
# -*- coding: utf-8 -*-

from datetime import datetime

tmpl = """/// %s
#include "RCounterXY.h"
#include "../../Common/ME/BQED.h"
#include "../../Common/Color.hpp"

#define init cdbl s = sp + q2;\\
cdbl f = 4.*sp*sp/s * Color::CA;

"""%("auto-generated by build.py on {0:%Y}/{0:%m}/{0:%d} {0:%H}:{0:%M}:{0:%S}".format(datetime.now()))
for proj in ["F2_VV", "F2_AA", "FL_VV", "FL_AA","x2g1_VV", "x2g1_AA", "xF3_VA", "g4_VA", "gL_VA"]:
    tmpl +="""
cdbl FullyDiff::ME::RCounterXY_%s(cdbl m2, cdbl q2, cdbl sp, cdbl t1) {
init
return f * Common::ME::BQED_%s(m2,q2,sp,t1);
}
"""%(proj,proj)

with open("../../src/FullyDiff/ME/RCounterXY.cpp", "w") as f:
	f.write(tmpl)
	f.close()
