#!/usr/bin/python
# -*- coding: utf-8 -*-

from datetime import datetime

tmpl = """/// %s
#include "RCounterXY.h"
#include "../../Common/ME/BQED.h"
#include "../../Common/Color.hpp"

#define build(proj) cdbl FullyDiff::ME::RCounterXY_##proj(cdbl m2, cdbl q2, cdbl sp, cdbl t1) {\\
cdbl s = sp + q2;\\
cdbl f = 4.*sp*sp/s * Color::CA;\\
return f * Common::ME::BQED_##proj(m2,q2,sp,t1);\\
}

interateAllProj(build)

"""%("auto-generated by build.py on {0:%Y}/{0:%m}/{0:%d} {0:%H}:{0:%M}:{0:%S}".format(datetime.now()))

with open("../../src/FullyDiff/ME/RCounterXY.cpp", "w") as f:
	f.write(tmpl)
	f.close()
