#!/usr/bin/python
# -*- coding: utf-8 -*-

from datetime import datetime

tmpl = """/// %s
#include "A1Counter.h"

#define Power(a,b) pow(a,b)
#define Cos(x) cos(x)
#define Sin(x) sin(x)
"""%("auto-generated by build.py on {0:%Y}/{0:%m}/{0:%d} {0:%H}:{0:%M}:{0:%S}".format(datetime.now()))
ls = []
for proj in ["F2_VV", "F2_AA", "FL_VV", "FL_AA","x2g1_VV", "x2g1_AA", "xF3_VA", "g4_VA", "gL_VA"]:
    l = "A1Counter_%s"%(proj)
    ls.append(l)
    tmpl +="""
cdbl FullyDiff::ME::%s({sig}) {{
%s
return {%s};
}}
"""%(l,"" if "gL_VA" == proj else "{init}",l)

fs={
 "sig": "cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2",
 "init": """cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));""",
}
for l in ls:
	with open(l+".c","r") as f:
		fs[l] = f.read()
		f.close()

with open("../../src/FullyDiff/ME/A1Counter.cpp", "w") as f:
	f.write(tmpl.format(**fs))
	f.close()
