#!/usr/bin/python
# -*- coding: utf-8 -*-

from datetime import datetime

tmpl = """/// %s
#include "RCounterY.h"
#include "RCounterXY.h"
#include "../../Common/Color.hpp"

#define Power(a,b) pow(a,b)
#define Cos(x) cos(x)
#define Sin(x) sin(x)

#define init cdbl s5 = q2 + x*sp;\\
cdbl beta5 = sqrt(1. - 4.*m2/s5);\\
cdbl t1c = -sp/2.*(1.-beta5*cos(Theta1));
#define checkThr(proj) if (1. - x < 1e-7) {{\\
cdbl t1sc = -sp/2.*(1. - sqrt(1.-4.*m2/(sp+q2))*cos(Theta1));\\
return RCounterXY_##proj(m2,q2,sp,t1sc);\\
}}

"""%("auto-generated by build.py on {0:%Y}/{0:%m}/{0:%d} {0:%H}:{0:%M}:{0:%S}".format(datetime.now()))
ls = []
for proj in ["F2_VV", "F2_AA", "FL_VV", "FL_AA","x2g1_VV", "x2g1_AA", "xF3_VA", "g4_VA", "gL_VA"]:
    l = "ROKCounterY_%s"%(proj)
    ls.append(l)
    tmpl +="""
cdbl FullyDiff::ME::RCounterY_%s(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {{
%s
return Color::CA * ({%s});
}}
"""%(proj,"" if "gL_VA" == proj else "init\ncheckThr("+proj+")",l)

fs={}
for l in ls:
	with open(l+".c","r") as f:
		fs[l] = f.read()
		f.close()

with open("../../src/FullyDiff/ME/RCounterY.cpp", "w") as f:
	f.write(tmpl.format(**fs))
	f.close()
