/// auto-generated by build.py on 2018/08/08 12:08:25
#include "A1.h"

#define Power(a,b) pow(a,b)

#define init cdbl u7 = q2 - sp - u1 - up;


cdbl FullyDiff::ME::A1_F2_VV(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (6*q2*Power(tp,3))/(Power(sp,2)*Power(u7,2)) + (Power(tp,2)*(6*q2*(2*m2 + sp + 4*t1)*u1 - 2*(3*Power(q2,2) + Power(sp,2) - 3*q2*(sp + 2*t1))*u7))/(Power(sp,2)*u1*Power(u7,2)) + (2*((2*m2 + q2)*Power(sp,2) + 6*q2*sp*t1 + 6*q2*Power(t1,2))*Power(sp*u7 + t1*(u1 + u7),2))/(Power(sp,2)*tp*Power(u1,2)*Power(u7,2)) + (tp*(-6*Power(q2,2)*(sp + 2*t1)*u1*u7 - 2*Power(sp,2)*u1*(sp + 2*t1 - u7)*u7 + q2*((Power(sp,2) + 18*sp*t1 + 42*Power(t1,2))*Power(u1,2) + 4*(Power(sp,2) + 9*sp*t1 + 9*Power(t1,2))*u1*u7 + (Power(sp,2) + 6*sp*t1 + 6*Power(t1,2) - 6*sp*u1)*Power(u7,2)) + 2*m2*(6*q2*(sp + 2*t1)*u1*(u1 + u7) + Power(sp,2)*(Power(u1,2) + Power(u7,2)))))/(Power(sp,2)*Power(u1,2)*Power(u7,2)) + (-2*Power(q2,2)*(Power(sp,2) + 6*sp*t1 + 6*Power(t1,2))*u1*u7 + 4*Power(m2,2)*Power(sp,2)*Power(u1 + u7,2) - Power(sp,2)*u1*u7*(2*Power(sp,2) + 4*Power(t1,2) + 2*t1*u1 + Power(u1,2) + 2*sp*(2*t1 + u1) - 2*t1*u7 + Power(u7,2)) + 2*m2*(2*Power(sp,2)*(u1 + u7)*(t1*u1 + (sp + t1 + u1)*u7) + q2*(6*sp*t1*Power(u1 + u7,2) + 6*Power(t1,2)*Power(u1 + u7,2) + Power(sp,2)*(Power(u1,2) + Power(u7,2)))) + 2*q2*(Power(sp,3)*u7*(u1 + u7) + 6*Power(t1,3)*(u1 + u7)*(3*u1 + u7) + 3*sp*t1*(u1*(u1 - u7)*u7 + 4*t1*(Power(u1,2) + 3*u1*u7 + Power(u7,2))) + Power(sp,2)*(u1*(u1 - 2*u7)*u7 + t1*(Power(u1,2) + 14*u1*u7 + 7*Power(u7,2)))))/(Power(sp,2)*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_F2_AA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (6*q2*Power(tp,3))/(Power(sp,2)*Power(u7,2)) + (2*((2*m2 + q2)*Power(sp,2) + 6*q2*sp*t1 + 6*q2*Power(t1,2))*Power(sp*u7 + t1*(u1 + u7),2))/(Power(sp,2)*tp*Power(u1,2)*Power(u7,2)) + (2*Power(tp,2)*(3*q2*(sp + 4*t1)*u1 - (3*Power(q2,2) + Power(sp,2) - 3*q2*(sp + 2*t1))*u7 + 6*m2*q2*(u1 + 2*u7)))/(Power(sp,2)*u1*Power(u7,2)) + (tp*(-6*Power(q2,2)*(sp + 2*t1)*u1*u7 - 2*Power(sp,2)*u1*(sp + 2*t1 - u7)*u7 + q2*((Power(sp,2) + 18*sp*t1 + 42*Power(t1,2))*Power(u1,2) + 4*(Power(sp,2) + 9*sp*t1 + 9*Power(t1,2))*u1*u7 + (Power(sp,2) + 6*sp*t1 + 6*Power(t1,2) - 6*sp*u1)*Power(u7,2)) + 2*m2*(6*q2*(sp + 2*t1)*u1*(u1 + u7) + sp*(12*u1*u7*(u1 + u7) + sp*(Power(u1,2) + 12*u1*u7 + Power(u7,2))))))/(Power(sp,2)*Power(u1,2)*Power(u7,2)) + (4*Power(m2,2)*q2*Power(sp,2)*Power(u1 + u7,2) + 2*m2*(2*q2*Power(sp,2)*(u1 + u7)*(t1*u1 + (sp + t1 + u1)*u7) + 2*Power(sp,2)*u1*u7*(2*Power(sp,2) + 2*sp*(u1 + u7) + Power(u1 + u7,2)) + Power(q2,2)*(6*sp*t1*Power(u1 + u7,2) + 6*Power(t1,2)*Power(u1 + u7,2) + Power(sp,2)*(Power(u1,2) + Power(u7,2)))) + q2*(-2*Power(q2,2)*(Power(sp,2) + 6*sp*t1 + 6*Power(t1,2))*u1*u7 - Power(sp,2)*u1*u7*(2*Power(sp,2) + 4*Power(t1,2) + 2*t1*u1 + Power(u1,2) + 2*sp*(2*t1 + u1) - 2*t1*u7 + Power(u7,2)) + 2*q2*(Power(sp,3)*u7*(u1 + u7) + 6*Power(t1,3)*(u1 + u7)*(3*u1 + u7) + 3*sp*t1*(u1*(u1 - u7)*u7 + 4*t1*(Power(u1,2) + 3*u1*u7 + Power(u7,2))) + Power(sp,2)*(u1*(u1 - 2*u7)*u7 + t1*(Power(u1,2) + 14*u1*u7 + 7*Power(u7,2))))))/(q2*Power(sp,2)*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_FL_VV(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (4*q2*Power(tp,3))/(Power(sp,2)*Power(u7,2)) + (4*q2*Power(tp,2)*((2*m2 + sp + 4*t1)*u1 + (-q2 + sp + 2*t1)*u7))/(Power(sp,2)*u1*Power(u7,2)) + (4*q2*(2*t1*(m2*(sp + t1) + t1*(2*sp + 3*t1))*Power(u1,2) + t1*u1*(2*(sp + t1)*(2*m2 - q2 + 2*sp + 4*t1) + sp*u1)*u7 + (sp + t1)*(2*t1*(m2 + sp + t1) - sp*u1)*Power(u7,2)))/(Power(sp,2)*Power(u1,2)*Power(u7,2)) + (8*q2*t1*(sp + t1)*Power(sp*u7 + t1*(u1 + u7),2))/(Power(sp,2)*tp*Power(u1,2)*Power(u7,2)) + (4*q2*tp*(t1*(3*sp + 7*t1)*Power(u1,2) + (Power(sp,2) + 6*sp*t1 + 6*Power(t1,2) - q2*(sp + 2*t1))*u1*u7 + (t1*(sp + t1) - sp*u1)*Power(u7,2) + 2*m2*(sp + 2*t1)*u1*(u1 + u7)))/(Power(sp,2)*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_FL_AA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (4*q2*Power(tp,3))/(Power(sp,2)*Power(u7,2)) + (4*q2*Power(tp,2)*((2*m2 + sp + 4*t1)*u1 + (4*m2 - q2 + sp + 2*t1)*u7))/(Power(sp,2)*u1*Power(u7,2)) + (8*(m2*Power(sp,2) + q2*t1*(sp + t1))*Power(sp*u7 + t1*(u1 + u7),2))/(Power(sp,2)*tp*Power(u1,2)*Power(u7,2)) + (4*(2*Power(m2,2)*q2*Power(sp,2)*Power(u1 + u7,2) + Power(q2,2)*(2*Power(t1,2)*(2*sp + 3*t1)*Power(u1,2) + t1*u1*(2*(sp + t1)*(-q2 + 2*sp + 4*t1) + sp*u1)*u7 + (sp + t1)*(2*t1*(sp + t1) - sp*u1)*Power(u7,2)) + m2*(2*q2*Power(sp,2)*(u1 + u7)*(t1*u1 + (sp + t1 + u1)*u7) + Power(sp,2)*u1*u7*(2*Power(sp,2) + 2*sp*(u1 + u7) + Power(u1 + u7,2)) + 2*Power(q2,2)*(-(Power(sp,2)*u1*u7) + sp*t1*Power(u1 + u7,2) + Power(t1,2)*Power(u1 + u7,2)))))/(q2*Power(sp,2)*Power(u1,2)*Power(u7,2)) + (4*tp*(q2*(t1*(3*sp + 7*t1)*Power(u1,2) + (Power(sp,2) + 6*sp*t1 + 6*Power(t1,2) - q2*(sp + 2*t1))*u1*u7 + (t1*(sp + t1) - sp*u1)*Power(u7,2)) + m2*(2*q2*(sp + 2*t1)*u1*(u1 + u7) + sp*(4*u1*u7*(u1 + u7) + sp*(Power(u1,2) + 4*u1*u7 + Power(u7,2))))))/(Power(sp,2)*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_x2g1_VV(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (2*q2*Power(tp,2)*(-u1 + u7))/(sp*u1*Power(u7,2)) - (tp*(q2*(4*m2 + sp + 6*t1)*Power(u1,2) - 2*(Power(q2,2) + Power(sp,2))*u1*u7 + (4*m2*q2 - 2*sp*u1 + q2*(sp + 2*(t1 + u1)))*Power(u7,2)))/(sp*Power(u1,2)*Power(u7,2)) + (-2*m2*sp*(2*sp + u1 + u7)*(Power(u1,2) + Power(u7,2)) - sp*u1*u7*(u1*(2*(sp + t1) + u1) - 2*t1*u7 + Power(u7,2)) + 2*q2*(-(t1*(sp + 2*t1)*Power(u1,2)) + u1*(Power(sp,2) + (sp + t1)*u1)*u7 - (Power(sp,2) + 3*sp*t1 + t1*(2*t1 + u1))*Power(u7,2)))/(sp*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_x2g1_AA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (2*q2*Power(tp,2)*(-u1 + u7))/(sp*u1*Power(u7,2)) - (tp*(Power(u1,2)*(q2*(sp + 6*t1) + 4*m2*(2*sp + u1)) - 2*(-4*m2*q2 + Power(q2,2) + Power(sp,2))*u1*u7 + (-2*(2*m2 + sp)*u1 + q2*(sp + 2*(t1 + u1)))*Power(u7,2)))/(sp*Power(u1,2)*Power(u7,2)) + (-(sp*u1*u7*(u1*(2*(sp + t1) + u1) - 2*t1*u7 + Power(u7,2))) - 2*m2*(2*sp + u1 + u7)*((sp + 2*t1)*Power(u1,2) + 2*sp*u1*u7 - (sp + 2*t1)*Power(u7,2)) + 2*q2*(-(t1*(sp + 2*t1)*Power(u1,2)) + u1*(Power(sp,2) + (sp + t1)*u1)*u7 - (Power(sp,2) + 3*sp*t1 + t1*(2*t1 + u1))*Power(u7,2)))/(sp*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_xF3_VA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (2*q2*Power(tp,2)*(u1 - u7))/(sp*u1*Power(u7,2)) + (2*q2*(sp + 2*t1)*Power(sp*u7 + t1*(u1 + u7),2))/(sp*tp*Power(u1,2)*Power(u7,2)) + (tp*(q2*(sp + 6*t1)*Power(u1,2) - 2*Power(q2,2)*u1*u7 + q2*(sp + 2*(t1 + u1))*Power(u7,2) - 2*sp*u1*u7*(sp + u7) + 4*m2*q2*u1*(u1 + u7)))/(sp*Power(u1,2)*Power(u7,2)) + (-2*Power(q2,2)*(sp + 2*t1)*u1*u7 + 2*m2*q2*(sp + 2*t1)*Power(u1 + u7,2) - sp*u1*u7*(2*Power(sp,2) + 2*sp*(2*t1 + u1) + (2*t1 + u1 - u7)*(u1 + u7)) + 2*q2*(Power(sp,2)*u7*(u1 + u7) + sp*(t1*Power(u1,2) + u1*(6*t1 + u1)*u7 + 3*t1*Power(u7,2)) + t1*(u1 + u7)*(u1*u7 + 2*t1*(2*u1 + u7))))/(sp*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_g4_VA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (6*q2*Power(tp,3))/(Power(sp,2)*Power(u7,2)) + (2*Power(tp,2)*(3*q2*(sp + 4*t1)*u1 - (3*Power(q2,2) + Power(sp,2) - 3*q2*(sp + 2*t1))*u7 + 6*m2*q2*(u1 + u7)))/(Power(sp,2)*u1*Power(u7,2)) + (tp*(-6*Power(q2,2)*(sp + 2*t1)*u1*u7 - 2*Power(sp,2)*u1*(sp + 2*t1 - u7)*u7 + 6*m2*(u1 + u7)*(q2*(sp + 2*t1)*(u1 + u7) + sp*u1*(2*sp + u1 + u7)) + q2*(6*Power(t1,2)*(u1 + u7)*(5*u1 + u7) + Power(sp,2)*(Power(u1,2) + 4*u1*u7 + Power(u7,2)) + 6*sp*(3*t1*Power(u1,2) + 6*t1*u1*u7 + (t1 - u1)*Power(u7,2)))))/(Power(sp,2)*Power(u1,2)*Power(u7,2)) + (Power(sp,2)*u1*u7*(2*sp*u1 + (2*t1 + u1 - u7)*(u1 + u7)) + 2*m2*sp*(u1 + u7)*(2*sp + u1 + u7)*(3*t1*(u1 + u7) + sp*(u1 + 2*u7)) + 2*q2*(Power(sp,3)*u7*(-u1 + u7) + 6*Power(t1,3)*Power(u1 + u7,2) + 3*sp*t1*(u1 + u7)*(-(u1*u7) + 2*t1*(u1 + 2*u7)) + Power(sp,2)*(-(u1*u7*(u1 + 2*u7)) + t1*(Power(u1,2) + 4*u1*u7 + 7*Power(u7,2)))))/(Power(sp,2)*Power(u1,2)*Power(u7,2));
}

cdbl FullyDiff::ME::A1_gL_VA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init
return (4*q2*Power(tp,3))/(Power(sp,2)*Power(u7,2)) + (4*q2*Power(tp,2)*(4*t1*u1 - q2*u7 + 2*t1*u7 + 2*m2*(u1 + u7) + sp*(u1 + u7)))/(Power(sp,2)*u1*Power(u7,2)) + (4*(sp*u7 + t1*(u1 + u7))*(2*q2*t1*(sp + t1)*u1 + q2*(2*t1*(sp + t1) - sp*u1)*u7 + m2*sp*(u1 + u7)*(2*sp + u1 + u7)))/(Power(sp,2)*Power(u1,2)*Power(u7,2)) + (4*tp*(m2*(u1 + u7)*(q2*(sp + 2*t1)*(u1 + u7) + sp*u1*(2*sp + u1 + u7)) + q2*(Power(sp,2)*u1*u7 + t1*(-2*q2*u1*u7 + t1*(u1 + u7)*(5*u1 + u7)) + sp*(-(u1*u7*(q2 + u7)) + t1*(3*Power(u1,2) + 6*u1*u7 + Power(u7,2))))))/(Power(sp,2)*Power(u1,2)*Power(u7,2));
}
