/// auto-generated by build.py on 2018/07/03 17:15:17
#include "A1Counter.h"

#define Power(a,b) pow(a,b)
#define Cos(x) cos(x)
#define Sin(x) sin(x)

cdbl FullyDiff::ME::A1Counter_F2_VV(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (-12*Power(q2,2)*t1c)/(Power(sp,2)*u1c*x) - (12*q2*(q2 + t1c*x))/(sp*u1c*x) + (sp*(-2*x*((-8*m2*q2 + 2*m2*u1c + q2*u1c)*x + t1c*u1c*(2 + (-2 + x)*x)) + 12*Power(beta5,2)*q2*s5*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2)))/(t1c*Power(u1c,2)*Power(x,2)) + (Power(sp,2)*(x*(2*m2*(2*m2 + q2)*x - t1c*u1c*(2 + (-2 + x)*x)) + 2*Power(beta5,2)*(2*m2 + q2)*s5*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2)))/(Power(t1c,2)*Power(u1c,2)*Power(x,2)) + (-2*x*(Power(q2,2)*u1c + 2*q2*t1c*(-4*m2 + 3*u1c)*x + Power(t1c,2)*u1c*(2 + (-2 + x)*x)) + 12*Power(beta5,2)*q2*s5*t1c*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2))/(t1c*Power(u1c,2)*Power(x,2));
}

cdbl FullyDiff::ME::A1Counter_F2_AA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (-12*Power(q2,2)*t1c)/(Power(sp,2)*u1c*x) - (12*q2*(q2 + t1c*x))/(sp*u1c*x) + (sp*(3*Power(beta5,2)*q2*s5*(-1 + x) - 2*x*((q2*u1c + 2*m2*(-4*q2 + u1c))*x + t1c*u1c*(2 + (-2 + x)*x)) - 3*Power(beta5,2)*q2*s5*(-1 + x)*(Cos(2*Theta1) - 2*Cos(2*Theta2)*Power(Sin(Theta1),2))))/(t1c*Power(u1c,2)*Power(x,2)) + (Power(sp,2)*(Power(beta5,2)*q2*(2*m2 + q2)*s5*(-1 + x) + 2*x*(4*Power(m2,2)*q2*x - q2*t1c*u1c*(2 + (-2 + x)*x) + 2*m2*(Power(q2,2)*x + 2*t1c*u1c*(2 + (-2 + x)*x))) - Power(beta5,2)*q2*(2*m2 + q2)*s5*(-1 + x)*(Cos(2*Theta1) - 2*Cos(2*Theta2)*Power(Sin(Theta1),2))))/(2.*q2*Power(t1c,2)*Power(u1c,2)*Power(x,2)) + (3*Power(beta5,2)*q2*s5*t1c*(-1 + x) - 2*x*(Power(q2,2)*u1c + 2*q2*t1c*(-4*m2 + 3*u1c)*x + Power(t1c,2)*u1c*(2 + (-2 + x)*x)) - 3*Power(beta5,2)*q2*s5*t1c*(-1 + x)*(Cos(2*Theta1) - 2*Cos(2*Theta2)*Power(Sin(Theta1),2)))/(t1c*Power(u1c,2)*Power(x,2));
}

cdbl FullyDiff::ME::A1Counter_FL_VV(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (8*Power(q2,2))/(Power(sp,2)*Power(x,2)) + (8*q2)/(sp*x) - (8*q2*(m2*Power(x,2) + Power(beta5,2)*s5*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2)))/(t1c*u1c*Power(x,3));
}

cdbl FullyDiff::ME::A1Counter_FL_AA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (-8*m2*sp)/(t1c*u1c) + (8*Power(q2,2))/(Power(sp,2)*Power(x,2)) + (8*q2)/(sp*x) - (8*q2*(2*m2*Power(x,2) + Power(beta5,2)*s5*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2)))/(t1c*u1c*Power(x,3)) + (4*m2*Power(sp,2)*(x*(2*m2*q2*x + t1c*u1c*(2 + (-2 + x)*x)) + 2*Power(beta5,2)*q2*s5*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2)))/(q2*Power(t1c,2)*Power(u1c,2)*Power(x,2));
}

cdbl FullyDiff::ME::A1Counter_x2g1_VV(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (2*m2*Power(sp,3)*(-2 + x))/(Power(t1c,2)*Power(u1c,2)) - (Power(sp,2)*(-4*m2 + u1c)*(-2 + x))/(t1c*Power(u1c,2)) - (4*q2*t1c*(-2 + x))/(sp*u1c*x) - (2*(-2 + x)*(2*q2 + t1c*x))/(u1c*x) - (2*sp*(-2 + x)*(q2*u1c + t1c*(-2*m2 + u1c)*x))/(t1c*Power(u1c,2)*x);
}

cdbl FullyDiff::ME::A1Counter_x2g1_AA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (2*m2*Power(sp,3)*(-2 + x))/(Power(t1c,2)*Power(u1c,2)) - (Power(sp,2)*(-4*m2 + u1c)*(-2 + x))/(t1c*Power(u1c,2)) - (4*q2*t1c*(-2 + x))/(sp*u1c*x) - (2*(-2 + x)*(2*q2 + t1c*x))/(u1c*x) - (2*sp*(-2 + x)*(q2*u1c + t1c*(-2*m2 + u1c)*x))/(t1c*Power(u1c,2)*x);
}

cdbl FullyDiff::ME::A1Counter_xF3_VA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (-4*Power(q2,2))/(sp*u1c*x) - (2*q2*(q2 + 2*t1c*x))/(t1c*u1c*x) + (Power(sp,2)*(x*(2*m2*q2*x - t1c*u1c*(2 + (-2 + x)*x)) + 2*Power(beta5,2)*q2*s5*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2)))/(Power(t1c,2)*Power(u1c,2)*Power(x,2)) + (sp*(-2*x*(q2*(-2*m2 + u1c)*x + t1c*u1c*(2 + (-2 + x)*x)) + 4*Power(beta5,2)*q2*s5*(-1 + x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2)))/(t1c*Power(u1c,2)*Power(x,2));
}

cdbl FullyDiff::ME::A1Counter_g4_VA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
cdbl s5 = q2 + sp*x;
cdbl beta5 = sqrt(1.-4.*m2/s5);
cdbl t1c = -1./2.*sp*(1.-beta5*cos(Theta1));
cdbl u1c = -1./2.*(s5-q2)*(1.+beta5*cos(Theta1));
return (-2*m2*Power(sp,3)*(-2 + x))/(Power(t1c,2)*Power(u1c,2)) + (Power(sp,2)*(-4*m2 + u1c)*(-2 + x))/(t1c*Power(u1c,2)) + (4*q2*(-2 + x))/(u1c*x) + (2*sp*(-2 + x)*(q2 + t1c*x))/(t1c*u1c*x);
}

cdbl FullyDiff::ME::A1Counter_gL_VA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {

return 0;
}
