/// auto-generated by build.py on 2018/08/14 10:57:32
#include "A2.h"

#define Power(a,b) pow(a,b)

#define init1 cdbl s5 = sp + tp + up;
#define init2 cdbl s = sp + q2;

cdbl FullyDiff::ME::A2_F2_VV(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init1
init2
return ((q2 + 2*s)/Power(s,2) + (18*q2)/Power(sp,2))*tp + s5*((-6*q2*(-2*m2 + sp - 2*t1)*tp)/(Power(sp,2)*Power(up,2)) + ((-2/s - (18*q2)/Power(sp,2))*tp)/up) + (6*q2*Power(s5,2)*tp)/(Power(sp,2)*Power(up,2)) + ((q2 - (12*q2*(m2*sp + (sp - t1)*t1))/Power(sp,2))*tp)/Power(up,2) + (tp*((12*q2*(-3*m2 + sp - 2*t1))/Power(sp,2) - (2*(2*(m2 + t1) + u1))/s))/up + (tp*((-6*q2*(-6*m2 + sp - 2*t1))/Power(sp,2) + (2*(-Power(q2,2) + m2*(q2 + 2*s) + s*t1 + q2*(s + t1 + u1)))/Power(s,2)) + (2*q2*(m2*sp + (sp - 6*t1)*t1)*tp)/(sp*Power(up,2)) + (tp*((12*q2*(2*m2*sp + (sp - t1)*t1))/Power(sp,2) - (6*Power(q2,2) + Power(s,2) - 4*m2*sp + 4*Power(t1,2) + 4*t1*u1 + 2*Power(u1,2) + 2*s*(t1 + u1) - 2*q2*(2*s + 4*t1 + 3*u1))/s))/up + (-(1/s) - (6*q2)/Power(sp,2))*tp*up)/s5 + ((2*q2*tp*(-6*m2*Power(s,2) + sp*Power(-q2 + t1 + u1,2)))/(Power(s,2)*sp) + (2*q2*Power(t1,2)*tp)/Power(up,2) - (2*tp*(m2*Power(s,2) + 2*q2*t1*(q2 - t1 - u1)))/(s*up) + 2*m2*(-(1/s) - (6*q2)/Power(sp,2))*tp*up)/Power(s5,2);
}

cdbl FullyDiff::ME::A2_F2_AA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init1
init2
return ((q2 + 2*s)/Power(s,2) + (18*q2)/Power(sp,2))*tp + s5*((-6*q2*(-2*m2 + sp - 2*t1)*tp)/(Power(sp,2)*Power(up,2)) + ((-2/s - (18*q2)/Power(sp,2))*tp)/up) + (6*q2*Power(s5,2)*tp)/(Power(sp,2)*Power(up,2)) + ((q2 - (12*q2*(m2*sp + (sp - t1)*t1))/Power(sp,2))*tp)/Power(up,2) + (tp*((12*q2*(-3*m2 + sp - 2*t1))/Power(sp,2) - (2*(2*(m2 + t1) + u1))/s))/up + (tp*((-6*q2*(-6*m2 + sp - 2*t1))/Power(sp,2) + (2*(-Power(q2,2) + m2*(q2 + 2*s) + s*t1 + q2*(s + t1 + u1)))/Power(s,2)) + (2*q2*(m2*sp + (sp - 6*t1)*t1)*tp)/(sp*Power(up,2)) - (tp*(6*Power(q2,2)*Power(sp,2) + 4*m2*sp*(-(s*sp) + q2*(-6*s + sp)) - 2*q2*(2*s*(Power(sp,2) + 3*sp*t1 - 3*Power(t1,2)) + Power(sp,2)*(4*t1 + 3*u1)) + Power(sp,2)*(Power(s,2) + 2*s*(t1 + u1) + 2*(2*Power(t1,2) + 2*t1*u1 + Power(u1,2)))))/(s*Power(sp,2)*up) + (-(1/s) - (6*q2)/Power(sp,2))*tp*up)/s5 + ((2*q2*tp*(-6*m2*Power(s,2) + sp*Power(-q2 + t1 + u1,2)))/(Power(s,2)*sp) + (2*q2*Power(t1,2)*tp)/Power(up,2) - (2*tp*(m2*Power(s,2) + 2*q2*t1*(q2 - t1 - u1)))/(s*up) + 2*m2*(-(1/s) - (6*q2)/Power(sp,2))*tp*up)/Power(s5,2);
}

cdbl FullyDiff::ME::A2_FL_VV(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init1

return (12*q2*tp)/Power(sp,2) + s5*((-4*q2*(-2*m2 + sp - 2*t1)*tp)/(Power(sp,2)*Power(up,2)) - (12*q2*tp)/(Power(sp,2)*up)) + (4*q2*Power(s5,2)*tp)/(Power(sp,2)*Power(up,2)) - (8*q2*(m2*sp + (sp - t1)*t1)*tp)/(Power(sp,2)*Power(up,2)) + (8*q2*(-3*m2 + sp - 2*t1)*tp)/(Power(sp,2)*up) + ((-4*q2*(-6*m2 + sp - 2*t1)*tp)/Power(sp,2) - (8*q2*Power(t1,2)*tp)/(sp*Power(up,2)) + (8*q2*(2*m2*sp + (sp - t1)*t1)*tp)/(Power(sp,2)*up) - (4*q2*tp*up)/Power(sp,2))/s5 + ((-8*m2*q2*tp)/sp - (8*m2*q2*tp*up)/Power(sp,2))/Power(s5,2);
}

cdbl FullyDiff::ME::A2_FL_AA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init1

return (12*q2*tp)/Power(sp,2) + s5*((-4*q2*(-2*m2 + sp - 2*t1)*tp)/(Power(sp,2)*Power(up,2)) - (12*q2*tp)/(Power(sp,2)*up)) + (4*q2*Power(s5,2)*tp)/(Power(sp,2)*Power(up,2)) - (8*q2*(m2*sp + (sp - t1)*t1)*tp)/(Power(sp,2)*Power(up,2)) + (8*q2*(-3*m2 + sp - 2*t1)*tp)/(Power(sp,2)*up) + ((-4*q2*(-6*m2 + sp - 2*t1)*tp)/Power(sp,2) - (8*q2*Power(t1,2)*tp)/(sp*Power(up,2)) + (8*q2*(2*m2*sp + (sp - t1)*t1)*tp)/(Power(sp,2)*up) - (4*q2*tp*up)/Power(sp,2))/s5 + ((-8*m2*q2*tp)/sp - (8*m2*q2*tp*up)/Power(sp,2))/Power(s5,2);
}

cdbl FullyDiff::ME::A2_x2g1_VV(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init1
init2
return -(((Power(q2,2) + q2*s + 2*Power(s,2))*tp)/(Power(s,2)*sp)) + s5*((-2*q2*tp)/(sp*Power(up,2)) + (2*q2*tp)/(s*sp*up)) + (q2*(-4*m2 + sp - 4*t1)*tp)/(sp*Power(up,2)) + (4*q2*(m2 + s + t1)*tp - 2*sp*tp*u1)/(s*sp*up) + ((-2*tp*(-Power(q2,3) + m2*(Power(q2,2) + q2*s + 2*Power(s,2)) + Power(s,2)*t1 - q2*s*u1 + Power(q2,2)*(2*s + t1 + u1)))/(Power(s,2)*sp) + (2*q2*(m2*sp + (sp - 2*t1)*t1)*tp)/(sp*Power(up,2)) + (tp*(6*Power(q2,3) + 4*m2*(Power(q2,2) + Power(s,2)) - 2*Power(q2,2)*(5*s + 4*t1 + 3*u1) + q2*(5*Power(s,2) + 14*s*t1 + 4*Power(t1,2) + 8*s*u1 + 4*t1*u1 + 2*Power(u1,2)) - s*(Power(s,2) + 2*s*(t1 + u1) + 2*u1*(2*t1 + u1))))/(s*sp*up) + ((q2 + s)*tp*up)/(s*sp))/s5 + ((-2*q2*tp*(Power(q2,3) + q2*(t1 + u1)*(2*s + t1 + u1) - Power(q2,2)*(s + 2*(t1 + u1)) + s*(2*m2*s - Power(t1 + u1,2))))/(Power(s,2)*sp) + (2*q2*Power(t1,2)*tp)/Power(up,2) - (2*tp*(m2*Power(s,2) + 2*q2*t1*(q2 - t1 - u1)))/(s*up) + (2*m2*(q2 + s)*tp*up)/(s*sp))/Power(s5,2);
}

cdbl FullyDiff::ME::A2_x2g1_AA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {


return 0;
}

cdbl FullyDiff::ME::A2_xF3_VA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {
init1
init2
return -(((Power(q2,2) + q2*s + 2*Power(s,2))*tp)/(Power(s,2)*sp)) + s5*((-2*q2*tp)/(sp*Power(up,2)) + (2*q2*tp)/(s*sp*up)) + (q2*(-4*m2 + sp - 4*t1)*tp)/(sp*Power(up,2)) + (4*q2*(m2 + s + t1)*tp - 2*sp*tp*u1)/(s*sp*up) + ((-2*tp*(-Power(q2,3) + m2*(Power(q2,2) + q2*s + 2*Power(s,2)) + Power(s,2)*t1 - q2*s*u1 + Power(q2,2)*(2*s + t1 + u1)))/(Power(s,2)*sp) + (2*q2*(m2*sp + (sp - 2*t1)*t1)*tp)/(sp*Power(up,2)) + (tp*(6*Power(q2,3) + 4*m2*(Power(q2,2) + Power(s,2)) - 2*Power(q2,2)*(5*s + 4*t1 + 3*u1) + q2*(5*Power(s,2) + 14*s*t1 + 4*Power(t1,2) + 8*s*u1 + 4*t1*u1 + 2*Power(u1,2)) - s*(Power(s,2) + 2*s*(t1 + u1) + 2*u1*(2*t1 + u1))))/(s*sp*up) + ((q2 + s)*tp*up)/(s*sp))/s5 + ((-2*q2*tp*(Power(q2,3) + q2*(t1 + u1)*(2*s + t1 + u1) - Power(q2,2)*(s + 2*(t1 + u1)) + s*(2*m2*s - Power(t1 + u1,2))))/(Power(s,2)*sp) + (2*q2*Power(t1,2)*tp)/Power(up,2) - (2*tp*(m2*Power(s,2) + 2*q2*t1*(q2 - t1 - u1)))/(s*up) + (2*m2*(q2 + s)*tp*up)/(s*sp))/Power(s5,2);
}

cdbl FullyDiff::ME::A2_g4_VA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {


return 0;
}

cdbl FullyDiff::ME::A2_gL_VA(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {


return 0;
}
