/// auto-generated by build.py on 2018/07/05 16:29:16
#include "RCounterY.h"
#include "RCounterXY.h"
#include "../../Common/Color.hpp"

#define Power(a,b) pow(a,b)
#define Cos(x) cos(x)
#define Sin(x) sin(x)

#define init cdbl s5 = q2 + x*sp;\
cdbl beta5 = sqrt(1. - 4.*m2/s5);\
cdbl t1c = -sp/2.*(1.-beta5*cos(Theta1));
#define checkThr(proj) if (1. - x < 1e-7) {\
cdbl t1sc = -sp/2.*(1. - sqrt(1.-4.*m2/(sp+q2))*cos(Theta1));\
return RCounterXY_##proj(m2,q2,sp,t1sc);\
}


cdbl FullyDiff::ME::RCounterY_F2_VV(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(F2_VV)
return Color::CA * ((-2*(4*Power(m2,2)*Power(sp,4)*(2 + (-2 + x)*x) + 2*m2*Power(sp,2)*(q2*(Power(sp,2) + 8*sp*t1c + 8*Power(t1c,2)) + 2*sp*t1c*(sp + t1c)*x)*(2 + (-2 + x)*x) + t1c*(sp + t1c)*(2*Power(q2,2)*(Power(sp,2) + 6*sp*t1c + 6*Power(t1c,2))*(2 + (-2 + x)*x) + 2*q2*sp*(Power(sp,2) + 6*sp*t1c + 6*Power(t1c,2))*x*(2 + (-2 + x)*x) + Power(sp,2)*(Power(sp,2) + 2*sp*t1c + 2*Power(t1c,2))*Power(1 + (-1 + x)*x,2))))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,2)) + (2*Power(beta5,2)*Power(sp,2)*((2*m2 + q2)*Power(sp,2) + 6*q2*sp*t1c + 6*q2*Power(t1c,2))*Power(-1 + x,2)*(q2 + sp*x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,4)));
}

cdbl FullyDiff::ME::RCounterY_F2_AA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(F2_AA)
return Color::CA * ((-2*(4*Power(m2,2)*q2*Power(sp,4)*(2 + (-2 + x)*x) + 2*m2*Power(sp,2)*(Power(q2,2)*(Power(sp,2) + 8*sp*t1c + 8*Power(t1c,2))*(2 + (-2 + x)*x) + 2*q2*sp*t1c*(sp + t1c)*x*(2 + (-2 + x)*x) - 2*Power(sp,2)*t1c*(sp + t1c)*Power(1 + (-1 + x)*x,2)) + q2*t1c*(sp + t1c)*(2*Power(q2,2)*(Power(sp,2) + 6*sp*t1c + 6*Power(t1c,2))*(2 + (-2 + x)*x) + 2*q2*sp*(Power(sp,2) + 6*sp*t1c + 6*Power(t1c,2))*x*(2 + (-2 + x)*x) + Power(sp,2)*(Power(sp,2) + 2*sp*t1c + 2*Power(t1c,2))*Power(1 + (-1 + x)*x,2))))/(q2*(q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,2)) + (2*Power(beta5,2)*Power(sp,2)*((2*m2 + q2)*Power(sp,2) + 6*q2*sp*t1c + 6*q2*Power(t1c,2))*Power(-1 + x,2)*(q2 + sp*x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,4)));
}

cdbl FullyDiff::ME::RCounterY_FL_VV(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(FL_VV)
return Color::CA * ((-16*q2*(2 + (-2 + x)*x)*(m2*Power(sp,2) + t1c*(sp + t1c)*(q2 + sp*x)))/((q2 + sp)*t1c*(sp + t1c)*Power(x,2)) + (8*Power(beta5,2)*q2*Power(sp,2)*Power(-1 + x,2)*(q2 + sp*x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2))/((q2 + sp)*t1c*(sp + t1c)*Power(x,4)));
}

cdbl FullyDiff::ME::RCounterY_FL_AA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(FL_AA)
return Color::CA * ((-8*(2*Power(m2,2)*q2*Power(sp,4)*(2 + (-2 + x)*x) + 2*Power(q2,2)*Power(t1c,2)*Power(sp + t1c,2)*(q2 + sp*x)*(2 + (-2 + x)*x) - m2*Power(sp,2)*t1c*(sp + t1c)*(-4*Power(q2,2)*(2 + (-2 + x)*x) - 2*q2*sp*x*(2 + (-2 + x)*x) + Power(sp,2)*Power(1 + (-1 + x)*x,2))))/(q2*(q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,2)) + (8*Power(beta5,2)*Power(sp,2)*(m2*Power(sp,2) + q2*t1c*(sp + t1c))*Power(-1 + x,2)*(q2 + sp*x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,4)));
}

cdbl FullyDiff::ME::RCounterY_x2g1_VV(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(x2g1_VV)
return Color::CA * ((2*sp*(Power(sp,2) + 2*sp*t1c + 2*Power(t1c,2))*(2 + x*(-3 + 2*x))*(2*m2*Power(sp,2) + t1c*(sp + t1c)*(2*q2 + sp*x)))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,2)));
}

cdbl FullyDiff::ME::RCounterY_x2g1_AA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(x2g1_AA)
return Color::CA * ((2*sp*(Power(sp,2) + 2*sp*t1c + 2*Power(t1c,2))*(2 + x*(-3 + 2*x))*(2*m2*Power(sp,2) + t1c*(sp + t1c)*(2*q2 + sp*x)))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,2)));
}

cdbl FullyDiff::ME::RCounterY_xF3_VA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(xF3_VA)
return Color::CA * ((-2*sp*(sp + 2*t1c)*(2*m2*q2*Power(sp,2)*(2 + (-2 + x)*x) + t1c*(sp + t1c)*(2*Power(q2,2)*(2 + (-2 + x)*x) + 2*q2*sp*x*(2 + (-2 + x)*x) + Power(sp,2)*Power(1 + (-1 + x)*x,2))))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,2)) + (2*Power(beta5,2)*q2*Power(sp,3)*(sp + 2*t1c)*Power(-1 + x,2)*(q2 + sp*x)*Power(Cos(Theta2),2)*Power(Sin(Theta1),2))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,4)));
}

cdbl FullyDiff::ME::RCounterY_g4_VA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {
init
checkThr(g4_VA)
return Color::CA * ((-2*Power(sp,2)*(sp + 2*t1c)*(2 + x*(-3 + 2*x))*(2*m2*Power(sp,2) + t1c*(sp + t1c)*(2*q2 + sp*x)))/((q2 + sp)*Power(t1c,2)*Power(sp + t1c,2)*Power(x,2)));
}

cdbl FullyDiff::ME::RCounterY_gL_VA(cdbl m2, cdbl q2, cdbl sp, cdbl x, cdbl Theta1, cdbl Theta2) {

return Color::CA * (0);
}
