/// auto-generated by build.py on 2018/07/05 10:34:51
#include "RCounterXY.h"
#include "../../Common/ME/BQED.h"
#include "../../Common/Color.hpp"

#define build(proj) cdbl FullyDiff::ME::RCounterXY_##proj(cdbl m2, cdbl q2, cdbl sp, cdbl t1) {\
cdbl s = sp + q2;\
cdbl f = 4.*sp*sp/s * Color::CA;\
return f * Common::ME::BQED_##proj(m2,q2,sp,t1);\
}

interateAllProj(build)