#!/usr/bin/python
# -*- coding: utf-8 -*-

from datetime import datetime
import re

tmpl = """/// %s
#include "ROK.h"

"""%("auto-generated by build.py on {0:%Y}/{0:%m}/{0:%d} {0:%H}:{0:%M}:{0:%S}".format(datetime.now()));
ls = [];
for proj in ["F2_VV", "F2_AA", "FL_VV","FL_AA","x2g1_VV","x2g1_AA","xF3_VA","g4_VA","gL_VA"]:
  l = "ROK_%s"%(proj)
  ls.append(l)
  tmpl +="""
cdbl FullyDiff::ME::%s(cdbl m2, cdbl q2, cdbl sp, cdbl t1, cdbl u1, cdbl tp, cdbl up) {{
{%s}
}}
"""%(l,l);

fs={};
for l in ls:
	with open("out"+l.replace("_","w")+".c","r") as f:
		opt = f.read()
		opt = opt.replace("_, \\\nZ","_, Z")
		opt = opt.replace(", Zlast_;",";")
		fs[l] = opt;
		f.close()

with open("../../../CodeLiteWS/LeptoProduction/src/FullyDiff/ME/ROK.cpp", "w") as f:
	f.write(tmpl.format(**fs))
	f.close()
