C. SETUP HBOOK FILES
      SUBROUTINE SHIST
      NBIN=30
      PI=2*ACOS(0.)
      CALL HBOOK1(10,'Q2 ',NBIN, 5.,100.,0.)
      CALL HBOOK1(20,'X  ',NBIN, 0.,  1.,0.)
      CALL HBOOK1(30,'Y  ',NBIN, 0.,  1.,0.)
      CALL HBOOK1(40,'W  ',NBIN,40.,260.,0.)
      CALL HBOOK1(50,'PHI',NBIN,-PI,  PI,0.)
      CALL HBOOK1(60,'PT ',NBIN, 0., 10.,0.)
      CALL HBOOK1(70,'ETA',NBIN,-3.,  3.,0.)
      RETURN
      END
C. FILL HBOOK FILES
      SUBROUTINE FHIST(WGT,P1,P2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION P1(0:3),P2(0:3)
      COMMON/INVAR/XBJ,XIMIN,XM2,Q2
      COMMON/BEAM/EPRO,EIEL
      COMMON/CUTS/ETAMAX,PTMIN,PTMAX
      COMMON/FLAGS/ISCALER,ISCALEF,IALPHAS,IFRAG
      COMMON/FRAGP/EPS,HFRAC,XMD
      IF(WGT.EQ.0D0)RETURN
      PT1=EPERP(P1)
      PT2=EPERP(P2)
      ETA1=SRAPID(P1)
      ETA2=SRAPID(P2)
      W=DSQRT(Q2*(1D0-XBJ)/XBJ)
      Y=Q2/XBJ/(4*EPRO*EIEL)
c      PHI=DABS(DATAN2(P1(2),P1(1))-DATAN2(P2(2),P2(1)))
c      IF(PHI.GT.2*DACOS(0D0))PHI=PHI-2*2*DACOS(0D0)
      PHI1=PHI(0,P1)
      PHI2=PHI(0,P2)
      PI=2*DACOS(0D0)
      IF( DABS(PHI1-PHI2).GT.PI )THEN
         IF(PHI1.GT.PHI2)THEN
            PHI1=PHI1-2*PI
         ELSE
            PHI2=PHI2-2*PI
         ENDIF
      ENDIF
      PHI12=PHI1-PHI2
      FFAC=0.5D0
      IF(IFRAG.EQ.1)FFAC=HFRAC
      TMP=WGT*FFAC
      WGT=0D0
      IF(DABS(ETA1).LT.ETAMAX)THEN
C         CALL HF1(60,REAL(PT1)  ,REAL(TMP))
         CALL HF1(60,REAL(PT1)  ,REAL(0.5*TMP/PT1))
      ENDIF
      IF( (PT1.GT.PTMIN).AND.(PT1.LT.PTMAX) )THEN
         CALL HF1(70,REAL(ETA1) ,REAL(TMP))
      ENDIF
      IF( (DABS(ETA1).LT.ETAMAX)
     &    .AND.(PT1.GT.PTMIN).AND.(PT1.LT.PTMAX) )THEN
         CALL HF1(10,REAL(Q2)   ,REAL(TMP))
         CALL HF1(20,REAL(XBJ)  ,REAL(TMP))
         CALL HF1(30,REAL(Y)    ,REAL(TMP))
         CALL HF1(40,REAL(W)    ,REAL(TMP))
         CALL HF1(50,REAL(PHI12),REAL(TMP))
C         CALL HF1(60,REAL(PT1)  ,REAL(TMP))
C         CALL HF1(70,REAL(ETA1) ,REAL(TMP))
         WGT=TMP
      ENDIF
      IF(DABS(ETA2).LT.ETAMAX)THEN
C         CALL HF1(60,REAL(PT2)  ,REAL(TMP))
         CALL HF1(60,REAL(PT2)  ,REAL(0.5*TMP/PT2))
      ENDIF
      IF( (PT2.GT.PTMIN).AND.(PT2.LT.PTMAX) )THEN
         CALL HF1(70,REAL(ETA2) ,REAL(TMP))
      ENDIF
      IF( (DABS(ETA2).LT.ETAMAX)
     &    .AND.(PT2.GT.PTMIN).AND.(PT2.LT.PTMAX) )THEN
         CALL HF1(10,REAL(Q2)   ,REAL(TMP))
         CALL HF1(20,REAL(XBJ)  ,REAL(TMP))
         CALL HF1(30,REAL(Y)    ,REAL(TMP))
         CALL HF1(40,REAL(W)    ,REAL(TMP))
         CALL HF1(50,REAL(PHI12),REAL(TMP))
C         CALL HF1(60,REAL(PT2)  ,REAL(TMP))
C         CALL HF1(70,REAL(ETA2) ,REAL(TMP))
         WGT=WGT+TMP
      ENDIF
      RETURN
      END
C. OUTPUT HBOOK FILES
      SUBROUTINE WHIST(PREF)
      CHARACTER * 25 PREF,FNAME
      REAL BINSIZ(7)
      PI=2*ACOS(0.)
      NBIN=30
      BINSIZ(1)=95./REAL(NBIN)
      BINSIZ(2)=1./REAL(NBIN)
      BINSIZ(3)=1./REAL(NBIN)
      BINSIZ(4)=220./REAL(NBIN)
      BINSIZ(5)=2*PI/REAL(NBIN)
      BINSIZ(6)=10./REAL(NBIN)
      BINSIZ(7)=6./REAL(NBIN)
      CALL STRCAT(PREF,'q2.out',FNAME)
      CALL LISDAT(10,FNAME,BINSIZ(1),NBIN,1.)
      CALL STRCAT(PREF,'x.out',FNAME)
      CALL LISDAT(20,FNAME,BINSIZ(2),NBIN,1.)
      CALL STRCAT(PREF,'y.out',FNAME)
      CALL LISDAT(30,FNAME,BINSIZ(3),NBIN,1.)
      CALL STRCAT(PREF,'w.out',FNAME)
      CALL LISDAT(40,FNAME,BINSIZ(4),NBIN,1.)
      CALL STRCAT(PREF,'phi.out',FNAME)
      CALL LISDAT(50,FNAME,BINSIZ(5),NBIN,1.)
      CALL STRCAT(PREF,'pt.out',FNAME)
      CALL LISDAT(60,FNAME,BINSIZ(6),NBIN,1.)
      CALL STRCAT(PREF,'eta.out',FNAME)
      CALL LISDAT(70,FNAME,BINSIZ(7),NBIN,1.)
      CALL HISTDO
      RETURN
      END
C.
C.  THIS ROUTINE STORES HISTOGRAM ENTRIES FROM HBOOK
C.
C.  ID  =  HBOOK HISTOGRAM ID
C.  TI  =  NAME FOR THE DATA FILE
C.  BW  =  BIN WIDTH
C.  NC  =  NUMBER OF BINS
C.  TOT =  OPTIONAL NORMALIZATION FACTOR
C.
      SUBROUTINE LISDAT(ID,TI,BW,NC,TOT)
      CHARACTER*(*) TI
      OPEN(UNIT=20,NAME=TI,STATUS='UNKNOWN')
      DO 10 I=1,NC
         CALL HIX(ID,I,X)
         X=X+0.5*BW
         Y=HI(ID,I)/(BW*TOT)
         WRITE(20,*) X,Y
 10   CONTINUE
      CLOSE(20)
      RETURN
      END
