.PHONY: clean All

All:
	@echo "----------Building project:[ ElProduction - Py27 ]----------"
	@cd "ElProduction" && "$(MAKE)" -f  "ElProduction.mk" PrePreBuild && "$(MAKE)" -f  "ElProduction.mk"
clean:
	@echo "----------Cleaning project:[ ElProduction - Py27 ]----------"
	@cd "ElProduction" && "$(MAKE)" -f  "ElProduction.mk" clean
